# Generated by Django 4.1.2 on 2023-04-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juegos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreJ', models.CharField(max_length=200)),
                ('ano', models.DateField()),
                ('imagen', models.ImageField(upload_to='juegos/images/')),
            ],
        ),
    ]
